// Importing the `LayoutServerLoad` type from the $types module, which is typically
// generated by a framework like SvelteKit for type safety in server-side load functions.
import type { LayoutServerLoad } from './$types';

// Defining the `load` function as a server load function. It conforms to the `LayoutServerLoad` type
// and is marked as `async` because it involves asynchronous operations.
export const load: LayoutServerLoad = async ({ locals: { safeGetSession }, cookies }) => {

    // Destructuring `safeGetSession` from the `locals` object.
    // `safeGetSession` is expected to be a function that retrieves the current session and user details.
    const { session } = await safeGetSession();

    // Returning an object containing the session, user, and all cookies.
    // This object will be accessible in the layout for rendering or further use.
    return {
        session, // Contains session data, such as authentication status or session-specific details.
        cookies: cookies.getAll() // Retrieves all cookies as an array of key-value pairs.
    };
};
